### ISSUE TITLE
Vim colorschemes backgrounds are incorrect

### ISSUE THREAD

**Issue by aig787** [railsware/upterm#962] opened 2017-01-30 19:31 UTC
It seems that vim colorschemes are not able to change the background to match the theme.

Black-Screen vs iTerm2
![screen shot 2017-01-30 at 11 24 49 am](https://cloud.githubusercontent.com/assets/4955443/22437975/0b3fd036-e6df-11e6-81ad-315c78684d0a.png)

**Comment by odedlaz** [comment] 2017-02-22 07:40
I believe that's b cause your terminal doesn't support true colors while black screen, does.

**Comment by Fuzen-py** [comment] 2017-04-10 13:37
I can also confirm the color issue (terminal uses true colors and its enabled in vim)
![image](https://cloud.githubusercontent.com/assets/17859309/24864079/220a24dc-1dd1-11e7-8719-47cb0e260769.png)

**Comment by aftaylor2** [comment] 2017-05-03 16:01
In Sierra, I'm unable to display my vim color scheme.  It works in iTerm2.

**Comment by vshatskyi** [comment] 2017-05-16 20:08
Can't reproduce. Which colorscheme do you use, @aig787?

**Comment by vshatskyi** [comment] 2017-05-16 20:08
Can't reproduce. Which colorscheme do you use, @aig787?

**Comment by aig787** [comment] 2017-05-17 15:03
I use the jellybeans colorscheme pulled in from 'flazz/vim-colorschemes' via vundle.

**Comment by Fuzen-py** [comment] 2017-05-18 17:02
![image](https://cloud.githubusercontent.com/assets/17859309/26214368/1b5e7a9a-3bca-11e7-9946-10a019e446a8.png)
Still getting some weird graphical bugs, here is my [vim config](https://github.com/Fuzen-py/VimFiles/blob/NeoVim/fuzens_config.vim).

**Comment by vlad-shatskyi** [comment] 2017-07-15 12:30
TODO

[ ] Cursor is one line lower than it should be.

**Comment by vlad-shatskyi** [comment] 2017-07-15 14:54
@aig787, @Fuzen-py, @aftaylor2 should be fixed in master.

**Closed by vlad-shatskyi** 2017-07-15 14:54 UTC
Labels: Bug: Confirmed, Priority: High
