### ISSUE TITLE
`!$` shortcut doesn't work in terminal , #could .. #should

### ISSUE THREAD

**Issue by slash** [railsware/upterm#1236] opened 2017-09-24 18:38 UTC
it should

<img width="367" alt="upterm 2017-09-24 20-37-21" src="https://user-images.githubusercontent.com/15662/30785541-4f431e02-a168-11e7-9e47-b699d38e37b9.png">

**Comment by vlad-shatskyi** [comment] 2017-09-25 09:28
A duplicate of https://github.com/railsware/upterm/issues/1009

**Closed by vlad-shatskyi** 2017-09-25 09:28 UTC
