### ISSUE TITLE
How to change home directory in the program?

### ISSUE THREAD

**Issue by voyga** [railsware/upterm#1233] opened 2017-09-23 16:35 UTC
It seems to remember the home directory I first launch the program, now I changed my home directory name, and it says `chdir(2) failed.: No such file or directory`

**Comment by vlad-shatskyi** [comment] 2017-09-23 21:09
A duplicate of https://github.com/railsware/upterm/issues/1176. Please remove `~/.upterm/presentWorkingDirectory` as a workaround.

**Closed by vlad-shatskyi** 2017-09-23 21:09 UTC
