### ISSUE TITLE
!! command not working

### ISSUE THREAD

**Issue by CptFox** [railsware/upterm#1186] opened 2017-08-30 07:23 UTC
I've just found out that the !! command (which returns the last run command, pretty useful for situations like this one.
```
$ do stuff  
Nope, you don't have the rights  
$ sudo !!  
Okay now I'll do it```

Maybe this could be implemented like a simple regex to replace ' !! ' with the last ran command?

**Comment by vlad-shatskyi** [comment] 2017-08-30 12:58
It's more complex than that, @CptFox. Closing as a duplicate of https://github.com/railsware/upterm/issues/1009

**Closed by vlad-shatskyi** 2017-08-30 12:58 UTC
