### ISSUE TITLE
proxy settings

### ISSUE THREAD

**Issue by afarbmangit** [railsware/upterm#1199] opened 2017-09-09 11:37 UTC
Cannot find how to set proxy. Does this app reads bash_profile on Mac?

**Comment by vlad-shatskyi** [comment] 2017-09-22 16:20
Could you please provide more details? How do you set this proxy in Bash?

**Comment by afarbmangit** [comment] 2017-09-22 16:59
Here is the script I have in my .bash_profile (which works in normal mac term and iTerm:

function proxy_all() {  
  local proxies=( HTTP_PROXY https_proxy HTTPS_PROXY ftp_proxy FTP_PROXY all_proxy ALL_PROXY )  
  local cmd=''  
  for i in "${proxies[@]}"  
  do  
      export $i="$http_proxy"  
  done  
}  
  
function proxy_on() {    
  export EID="USER_ID"   
  local PW="USER_PWD" 
  PW=$(sed -e 's/%/%25/g' <<< $PW)  
  PW=$(sed -e 's/@/%40/g' <<< $PW)  
  PW=$(sed -e 's/:/%3A/g' <<< $PW)  
  PW=$(sed -e "s/'/%27/g" <<< $PW)  
  PW=$(sed -e 's/&/%26/g' <<< $PW)  
  PW=$(sed -e 's/\$/%24/g' <<< $PW)  
  PW=$(sed -e 's/#/%23/g' <<< $PW)  
  PW=$(sed -e 's/"/%22/g' <<< $PW)  
  PW=$(sed -e 's/!/%21/g' <<< $PW)  
  PW=$(sed -e 's/ /%20/g' <<< $PW)  
  export http_proxy="proxy url here"  
  proxy_all    
  [ "-s" != "$1" ] && echo "Proxy enabled"    
}    
  
function proxy_off() {    
  unset http_proxy    
  proxy_all  
  [ "-s" != "$1" ] && echo "Proxy disabled"    
}   
  
# The rest is optional  
# Allows you to use proxy on or proxy off instead of proxy_on or proxy_off  
function proxy() {  
  eval "proxy_$1 $2"  
}  
  
# Enables the proxy for every terminal window  
proxy_on -s 
  
  
# Reveal your current proxy settings  
function proxy_info() {  
  local proxies=( http_proxy HTTP_PROXY https_proxy HTTPS_PROXY ftp_proxy FTP_PROXY all_proxy ALL_PROXY )  
  local ds='$'  
  for i in "${proxies[@]}"  
  do  
    printf "$i\t"  
    eval "echo $ds$i"  
  done  
} 

proxy on

**Comment by vlad-shatskyi** [comment] 2017-09-22 21:12
Got it. Unfortunately, functions aren't supported in Upterm at the moment.

**Comment by vlad-shatskyi** [comment] 2017-09-22 21:14
A duplicate of https://github.com/railsware/upterm/issues/1228

**Closed by vlad-shatskyi** 2017-09-22 21:14 UTC
Labels: Elaboration Requested
